src/accounts/urls.py
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.models import AbstractUser

from accounts.validators import validate_phone_number


class User(AbstractUser):
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    surname = models.CharField(max_length=210, blank=True)
    phone_number = models.CharField(null=False,
                                    max_length=20,
                                    validators=[validate_phone_number],
                                    default="+38(098)000-0000")
    image = models.ImageField(default='default.png', upload_to='accounts')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        image = Image.open(self.image)
        image.thumbnail((300, 300), Image.ANTIALIAS)
        image.save(self.image.path)

src/consultations/models.py
from django.db import models

# Create your models here.

src/core/models.py
from django.db import models

# Create your models here.

src/groups/models.py
from django.db import models

# Create your models here.

src/lessons/models.py
from django.db import models

# Create your models here.

src/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm

from accounts.models import User


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'register__input'
            })


class AccountLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'register__input'
            })


class AccountUpdateForm(UserChangeForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = '__all__'

src/accounts/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm, AccountLoginForm
from accounts.models import User


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User registered successfully')
        return result


class AccountLoginView(LoginView):
    template_name = 'login.html'
    form_class = AccountLoginForm

    def form_valid(self, form):
        result = super().form_valid(form)
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'
    success_url = reverse_lazy('index')

    def get_redirect_url(self):
        return reverse('index')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(self.request, f'User {self.request.user} logged out')
        return super().dispatch(request, *args, **kwargs)


class AccountUpdateView(UpdateView):
    model = User
    template_name = 'profile.html'
    success_url = reverse_lazy('index')
    form_class = AccountUpdateForm

    def get_object(self, queryset=None):
        return self.request.user


class AccountPasswordChangeView(PasswordChangeView):
    template_name = 'password-change.html'
    success_url = reverse_lazy('index')

src/consultations/views.py
from django.shortcuts import render

# Create your views here.

src/core/views.py
from django.shortcuts import render

# Create your views here.

src/groups/views.py
from django.shortcuts import render

# Create your views here.

src/lessons/views.py
from django.shortcuts import render

# Create your views here.

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
       <section class="register">
            <div class="register__block">
                <form class="register__form" method="post">
                    {% csrf_token %}
                    <div class="register__title">
                        Вход
                    </div>
                    {{form.errors}}
                    <div class="register__item">
                        {{form.username.errors}}
                        {{form.username}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Логин
                        </span>
                    </div>
                    <div class="register__item">
                        {{form.password.errors}}
                        {{form.password}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Пароль
                        </span>
                    </div>
                    <div class="register__nav">
                        <div class="register__check">
                            <input class="register__inpCheckbox" id="ckb1" type="checkbox" name="remember-me">
                            <label class="register__lblCheckbox" for="ckb1">
                                <img src="{% static 'img/icon//check.svg' %}" class="img-svg" alt="">
                                Запомнить меня
                            </label>
                        </div>
                        <div class="register__forgot">
                            <a href="#">
                                Забыли пароль?
                            </a>
                        </div>
                    </div>
                    <button type="submit" class="register__btn">
                        Войти
                    </button>
                    <div class="register__text">
                        У Вас нет аккаунта? <a href="{% url 'accounts:registration' %}">Регистрация</a>
                    </div>
                </form>

            </div>
       </section>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}
    <h2>You logged out</h2>
{% endblock %}
{% block content %}
<div class="create">
    <a class="btn btn-success" href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock %}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
                <form method="POST" class="settings" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="settings__title">
                        Налаштування
                    </div>
                    <div class="settings__block">
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Деталі:
                            </div>
                            {{form.errors}}
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Аватар</label>
                                    <div class="change__image">
                                        <img src="{{ user.image.url }}" alt="" class="change__photo">
                                        <img class="change__delete img-svg" src="{% static 'img/icon/delete.svg' %}" alt="">
                                        <img class="change__edit img-svg" src="{% static 'img/icon/edit.svg' %}" alt="">
                                    </div>

                                </div>
                                <div class="change__item">
                                    <label for="">Прізвище</label>
                                    {{ form.surname.errors }}
                                    {{ form.surname }}
                                </div>
                                <div class="change__item">
                                    <label for="">Ім'я</label>
                                    {{ form.first_name.errors }}
                                    {{ form.first_name }}
                                </div>
                                <div class="change__item">
                                    <label for="">По-батькові</label>
                                    {{ form.last_name.errors }}
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Інформація:
                            </div>
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Логін</label>
                                    {{ form.username.errors }}
                                    {{ form.username }}
                                </div>
                                <div class="change__item">
                                    <label for="">Електронна пошта</label>
                                    {{ form.email.errors }}
                                    {{ form.email }}
                                </div>
                                <div class="change__item">
                                    <label for="">Телефон</label>
                                    {{ form.phone_number.errors }}
                                    {{ form.phone_number }}
                                </div>
                                <div class="change__item">
                                    <label for="">Група</label>
                                    <div class="change__text">
                                        РЗ-171
                                    </div>
                                </div>
                                <div class="change__item">
                                    <label for="">Курс</label>
                                    <div class="change__text">
                                        4
                                    </div>
                                </div>
                                <div class="change__item">
                                    <label for="">Семестр</label>
                                    <div class="change__text">
                                        8
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Зміна паролю:
                            </div>
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Поточний пароль</label>
                                    <input type="password" name="" id="" placeholder="">
                                </div>
                                <div class="change__item">
                                    <label for="">Новий пароль</label>
                                    <input type="password" name="" id="" placeholder="">
                                </div>
                                <div class="change__item">
                                    <label for="">Повторити новий пароль</label>
                                    <input type="password" name="" id="" placeholder="">
                                </div>
                            </div>
                        </div>
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Інше:
                            </div>
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Мова</label>
                                    <select class="change__select">
                                        <option value="ukr">Українська</option>
                                        <option value="rus">Русская</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="settings__save">
                        <button class="settings__btn" type="submit">
                            <img class="img-svg" src="{% static 'img/icon/floppy-disk.svg' %}" alt="">
                            Зберегти
                        </button>
                    </div>
                </form>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
       <section class="register">
            <div class="register__block">
                <form class="register__form" method="post">
                    <div class="register__title">
                        Регистрация
                    </div>
                    {% csrf_token %}
                    {{form.as_p}}
                    {{form.date_joined}}
                    {{form.username.errors}}
                    <div class="register__item">
                        {{form.username}}

                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Nickname
                        </span>
                    </div>
                    {{form.email.errors}}
                    <div class="register__item">
                        {{form.email}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            E-mail
                        </span>
                    </div>
                    {{form.password1.errors}}
                    <div class="register__item">
                        {{form.password1}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Пароль
                        </span>
                    </div>
                    {{form.password2.errors}}
                    <div class="register__item">
                        {{form.password2}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Повтороите пароль
                        </span>
                    </div>
                    <button type="submit" class="register__btn">
                        Зарегистрироваться
                    </button>
                    <div class="register__text">
                        У Вас уже есть аккаунт? <a href="{% url 'accounts:login' %}">Войти</a>
                    </div>
                </form>
                
            </div>
       </section>
{% endblock %}

src/templates/auth.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="img/icon/favicon1.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap&subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap&subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="css/style.min.css">
    <title>LMS</title>

    <body>

       <section class="register">
            <div class="register__block">
                <form class="register__form">
                    <div class="register__title">
                        Вход
                    </div>
                    <div class="register__item">
                        <input type="text" class="register__input" placeholder="">
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Логин
                        </span>
                    </div>
                    <div class="register__item">
                        <input type="text" class="register__input" placeholder="">
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Пароль
                        </span>
                    </div>
                    <div class="register__nav">
                        <div class="register__check">
                            <input class="register__inpCheckbox" id="ckb1" type="checkbox" name="remember-me">
                            <label class="register__lblCheckbox" for="ckb1">
                                <img src="img/icon//check.svg" class="img-svg" alt="">
                                Запомнить меня
                            </label>
                        </div>
                        <div class="register__forgot">
                            <a href="#">
                                Забыли пароль?
                            </a>
                        </div>
                    </div>
                    <button type="submit" class="register__btn">
                        Войти
                    </button>
                    <div class="register__text">
                        У Вас нет аккаунта? <a href="register.html">Регистрация</a>
                    </div>
                </form>
                
            </div>             
       </section>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script src="js/maskinput.js"></script>
        <script src="js/script.js"></script>
    </body>

</html>

src/templates/base.html
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="img/icon/favicon1.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap&subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap&subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <title>LMS</title>

    <body>

       <section class="main">
            <nav class="menu">
                <div class="menu__title title">
                    Одеський Національний
                    Політехнічний Університет
                </div>
                <ul class="menu__list">
                    <a href="shedule.html" class="menu__item">
                        <img src="{% static 'img/icon/calendar.svg' %}" class="img-svg" alt="">
                        <span>Розклад занять</span>
                    </a>
                    <a href="" class="menu__item">
                        <img src="{% static 'img/icon/calendar-time.svg' %}" class="img-svg" alt="">
                        <span>Розклад консультацій</span>
                    </a>
                    <a href="journal.html" class="menu__item">
                        <img src="{% static 'img/icon/notebook.svg' %}" class="img-svg" alt="">
                        <span>Електронний журнал</span>
                    </a>
                    <a href="" class="menu__item">
                        <img src="{% static 'img/icon/group.svg' %}" class="img-svg" alt="">
                        <span>Группа</span>
                    </a>
                    <a href="settings.html" class="menu__item">
                        <img src="{% static 'img/icon/settings.svg' %}" class="img-svg" alt="">
                        <span>Налаштування</span>
                    </a>
                </ul>
            </nav>
            <div class="content">
                <header class="header">
                    <div class="header__cath">
                        Кафедра ІУЗІС
                    </div>
                    {% if user.is_authenticated %}
                    <div class="header__profile">
                        <div class="header__item">
                            <div class="header__name">
                                <a href="{% url 'accounts:profile' %}">{{user.surname}} {{user.first_name}}</a>
                            </div>
                            <div class="header__group">
                                {{user.username}}
                            </div>
                        </div>
                        <div class="header__item header__icon">
                            <img src="{{ user.image.url }}" alt="">
                        </div>
                        <div class="header__item">
                            <form action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    <div><a href="{% url 'accounts:registration' %}">Регистрация</a></div>
                    {% endif %}
                </header>
                    {% block content %}

                    {% endblock %}
            </div>
       </section>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script src="{% static 'js/maskinput.js' %}"></script>
        <script src="{% static 'js/script.js' %}"></script>
    </body>

</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
{% endblock %}